#!/usr/bin/env bash
set -euo pipefail

DEFAULT_BG="#282a36"
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
CONF_PATH="$CONF_DIR/local-status.conf"

bg="${TMUX_STATUS_BG:-$DEFAULT_BG}"

# validate color: #RRGGBB
if [[ ! "$bg" =~ ^#[0-9A-Fa-f]{6}$ ]]; then
  echo "warn: invalid TMUX_STATUS_BG '$bg', fallback to $DEFAULT_BG" >&2
  bg="$DEFAULT_BG"
fi

# 派生颜色：基于背景，保持 hue，降低饱和度，微调亮度
readarray -t derived < <(python - <<'PY'
import colorsys, sys

bg = sys.argv[1]
if not bg.startswith("#") or len(bg) != 7:
    print("")
    sys.exit(1)

def hex_to_rgb(hex_str):
    r = int(hex_str[1:3], 16) / 255.0
    g = int(hex_str[3:5], 16) / 255.0
    b = int(hex_str[5:7], 16) / 255.0
    return r, g, b

def rgb_to_hex(rgb):
    return "#{:02x}{:02x}{:02x}".format(
        int(max(0, min(1, rgb[0])) * 255 + 0.5),
        int(max(0, min(1, rgb[1])) * 255 + 0.5),
        int(max(0, min(1, rgb[2])) * 255 + 0.5),
    )

r, g, b = hex_to_rgb(bg)
h, l, s = colorsys.rgb_to_hls(r, g, b)

# 降低饱和度，保持色相
s = s * 0.45

def derive(lightness_scale):
    l2 = max(0, min(1, l * lightness_scale))
    r2, g2, b2 = colorsys.hls_to_rgb(h, l2, s)
    return rgb_to_hex((r2, g2, b2))

# 亮度微调：bar/inactive 略暗，active 略亮
bar_bg    = derive(0.94)  # -6%
inactive_bg = derive(0.94)
active_bg = derive(1.05)  # +5%

# 文本颜色：根据亮度自动选浅/深
fg_color = "#e5e5e5" if l < 0.5 else "#111111"

print(bar_bg)
print(inactive_bg)
print(active_bg)
print(fg_color)
PY
"$bg")

# 回退
if [[ "${#derived[@]}" -ne 4 || -z "${derived[0]}" ]]; then
  bar_bg="$bg"
  inactive_bg="$bg"
  active_bg="$bg"
  fg_color="#e5e5e5"
else
  bar_bg="${derived[0]}"
  inactive_bg="${derived[1]}"
  active_bg="${derived[2]}"
  fg_color="${derived[3]}"
fi

mkdir -p "$CONF_DIR"
cat >"$CONF_PATH" <<EOF
# Auto-generated by generate_local_status.sh
set -g @status_bg "$bg"
set -g @status_bar_bg "$bar_bg"
set -g @status_inactive_bg "$inactive_bg"
set -g @status_inactive_fg "$fg_color"
set -g @status_active_bg "$active_bg"
set -g @status_active_fg "$fg_color"
set -g @status_fg "$fg_color"
EOF

echo "tmux status colors written to $CONF_PATH (base: $bg, bar: $bar_bg)"
